#!/bin/bash

# Silverstripe CMS 6.x Installer Wrapper Script
# Runs composer create-project and configures .env interactively

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}"
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║          Silverstripe CMS Installer Wrapper                   ║"
echo "║                    for CMS 6.x                                ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Check if composer is installed
if ! command -v composer &> /dev/null; then
    echo -e "${RED}Error: Composer is not installed or not in PATH${NC}"
    exit 1
fi

# Check if we're in the right directory
if [ ! -d "$(pwd)" ]; then
    echo -e "${RED}Error: Invalid directory${NC}"
    exit 1
fi

# Check if directory is empty (except for hidden files)
if [ "$(ls -A 2>/dev/null | grep -v '^\.')" ]; then
    echo -e "${YELLOW}Warning: Current directory is not empty.${NC}"
    read -p "Continue anyway? (y/n): " continue_install
    if [[ ! "$continue_install" =~ ^[Yy]$ ]]; then
        echo "Installation cancelled."
        exit 0
    fi
fi

echo -e "${GREEN}Step 1: Running Composer create-project...${NC}"
echo ""

# Run composer create-project
composer create-project silverstripe/installer . --no-interaction

# Check if .env.example exists
if [ ! -f ".env.example" ]; then
    echo -e "${RED}Error: .env.example not found. Installation may have failed.${NC}"
    exit 1
fi

echo ""
echo -e "${GREEN}Step 2: Configuring environment (.env)${NC}"
echo -e "${YELLOW}Please provide the following configuration values:${NC}"
echo ""

# Database Configuration
echo -e "${BLUE}── Database Configuration ──${NC}"

read -p "Database Class [MySQLDatabase]: " db_class
db_class=${db_class:-MySQLDatabase}

read -p "Database Server [localhost]: " db_server
db_server=${db_server:-localhost}

read -p "Database Name: " db_name
while [ -z "$db_name" ]; do
    echo -e "${RED}Database name is required.${NC}"
    read -p "Database Name: " db_name
done

read -p "Database Username [root]: " db_username
db_username=${db_username:-root}

read -sp "Database Password: " db_password
echo ""

# Admin Configuration
echo ""
echo -e "${BLUE}── Admin Configuration ──${NC}"

read -p "Default Admin Username [admin]: " admin_username
admin_username=${admin_username:-admin}

while true; do
    read -sp "Default Admin Password: " admin_password
    echo ""
    if [ -z "$admin_password" ]; then
        echo -e "${RED}Admin password is required.${NC}"
        continue
    fi
    read -sp "Confirm Admin Password: " admin_password_confirm
    echo ""
    if [ "$admin_password" != "$admin_password_confirm" ]; then
        echo -e "${RED}Passwords do not match. Please try again.${NC}"
    else
        break
    fi
done

# Environment Type
echo ""
echo -e "${BLUE}── Environment Type ──${NC}"
echo "Options: dev, test, live"
read -p "Environment Type [dev]: " env_type
env_type=${env_type:-dev}

# Validate environment type
if [[ ! "$env_type" =~ ^(dev|test|live)$ ]]; then
    echo -e "${YELLOW}Invalid environment type. Defaulting to 'dev'.${NC}"
    env_type="dev"
fi

# Optional: Base URL
echo ""
echo -e "${BLUE}── Optional Settings ──${NC}"
read -p "Base URL (leave empty to skip): " base_url

# Create .env file
echo ""
echo -e "${GREEN}Step 3: Creating .env file...${NC}"

cat > .env << EOF
# Silverstripe CMS Environment Configuration
# Generated by ss-install.sh on $(date)
# https://docs.silverstripe.org/en/6/getting_started/environment_management/

# Database Configuration
SS_DATABASE_CLASS="${db_class}"
SS_DATABASE_SERVER="${db_server}"
SS_DATABASE_NAME="${db_name}"
SS_DATABASE_USERNAME="${db_username}"
SS_DATABASE_PASSWORD="${db_password}"

# Admin Configuration
SS_DEFAULT_ADMIN_USERNAME="${admin_username}"
SS_DEFAULT_ADMIN_PASSWORD="${admin_password}"

# Environment Type (dev|test|live)
SS_ENVIRONMENT_TYPE="${env_type}"
EOF

# Add base URL if provided
if [ -n "$base_url" ]; then
    echo "" >> .env
    echo "# Base URL" >> .env
    echo "SS_BASE_URL=\"${base_url}\"" >> .env
fi

# Set appropriate permissions on .env
chmod 600 .env

# Remove .env.example as it's no longer needed
rm -f .env.example

echo -e "${GREEN}✓ .env file created successfully${NC}"
echo -e "${GREEN}✓ .env.example removed${NC}"

# Summary
echo ""
echo -e "${BLUE}"
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                    Installation Complete!                     ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

echo -e "Configuration Summary:"
echo -e "  Database:     ${db_name}@${db_server}"
echo -e "  DB User:      ${db_username}"
echo -e "  Admin User:   ${admin_username}"
echo -e "  Environment:  ${env_type}"
if [ -n "$base_url" ]; then
    echo -e "  Base URL:     ${base_url}"
fi

echo ""
echo -e "${YELLOW}Next Steps:${NC}"
echo "  1. Ensure your database '${db_name}' exists"
echo "  2. Point your webserver to the 'public/' folder"
echo "  3. Visit your site to complete the database build"
echo "     Or run: vendor/bin/sake dev/build flush=1"
echo ""
echo -e "${GREEN}Happy developing with Silverstripe CMS!${NC}"
